Repository Buyhood/BuyHood, pull requests merged in 2025-06, with the labels that each got.

#49 refactor(MFLP-47): Product domain refactoring
  src/main/java/api/buyhood/domain/product/controller/ProductController.java
  src/main/java/api/buyhood/domain/product/repository/CategoryProductRepository.java
  src/main/java/api/buyhood/domain/product/repository/ProductRepository.java
  src/main/java/api/buyhood/domain/product/service/ProductService.java
Labels: feat, refactor

#50 refactor(MFLP-49): Refactoring the shop domain
  src/main/java/api/buyhood/domain/seller/repository/SellerRepository.java
  src/main/java/api/buyhood/domain/store/controller/StoreController.java
  src/main/java/api/buyhood/domain/store/dto/request/PatchStoreReq.java
  src/main/java/api/buyhood/domain/store/dto/request/RegisterStoreReq.java
  src/main/java/api/buyhood/domain/store/dto/response/GetStoreRes.java
  src/main/java/api/buyhood/domain/store/dto/response/PageStoreRes.java
  src/main/java/api/buyhood/domain/store/dto/response/RegisterStoreRes.java
  src/main/java/api/buyhood/domain/store/entity/Store.java
  src/main/java/api/buyhood/domain/store/repository/StoreRepository.java
  src/main/java/api/buyhood/domain/store/service/StoreService.java
  src/main/java/api/buyhood/global/common/exception/enums/StoreErrorCode.java
Labels: feat, refactor

#51 refactor(MFLP-51): Rename a class
  src/main/java/api/buyhood/domain/product/entity/ProductCategory.java
  src/main/java/api/buyhood/domain/product/repository/ProductCategoryRepository.java
  src/main/java/api/buyhood/domain/product/service/CategoryService.java
  src/main/java/api/buyhood/domain/product/service/ProductService.java
Labels: refactor

#52 feat(MFLP-52): Add a Store association to the Product entity and modify the related code
  src/main/java/api/buyhood/domain/product/controller/ProductController.java
  src/main/java/api/buyhood/domain/product/entity/Product.java
  src/main/java/api/buyhood/domain/product/repository/ProductRepository.java
  src/main/java/api/buyhood/domain/product/service/ProductService.java
  src/main/java/api/buyhood/domain/store/dto/response/GetStoreRes.java
  src/main/java/api/buyhood/domain/store/repository/StoreRepository.java
  src/main/java/api/buyhood/domain/store/service/StoreService.java
Labels: feat, refactor

#55 fix(MFLP-56): Add `@Secured` to ProductController
  src/main/java/api/buyhood/domain/product/controller/ProductController.java
Labels: bug

#56 refactor(MFLP-57): Refactor Get Order
  src/main/java/api/buyhood/domain/order/controller/OrderHistoryController.java
  src/main/java/api/buyhood/domain/order/dto/response/GetOrderRes.java
  src/main/java/api/buyhood/domain/order/repository/OrderHistoryRepository.java
  src/main/java/api/buyhood/domain/order/service/OrderHistoryService.java
Labels: refactor

#62 fix(MFLP-66): Remove `@Min` applied within the Category domain
  src/main/java/api/buyhood/domain/product/entity/Category.java
Labels: bug

#65 infra(INFRA-13~20) : deployment from AWS codedeploy && ssh
  .github/workflows/cd.yml
  appspec.yml
  build.gradle
Labels: infra

#68 feat(MFLP-62): Add payment success validation
  buyhood-global-core/buyhood-global-common/src/main/java/api/errorcode/PaymentErrorCode.java
  src/main/java/api/buyhood/domain/payment/controller/PaymentController.java
  src/main/java/api/buyhood/domain/payment/controller/PaymentRestController.java
  src/main/java/api/buyhood/domain/payment/dto/request/ValidPaymentReq.java
  src/main/java/api/buyhood/domain/payment/entity/Payment.java
  src/main/java/api/buyhood/domain/payment/service/PaymentService.java
  src/main/resources/templates/payment-portone.html
Labels: feat

#69 feat(MFLP-67): Developing Cancel Order
  buyhood-global-core/buyhood-global-common/src/main/java/api/errorcode/OrderErrorCode.java
  buyhood-global-core/buyhood-global-common/src/main/java/api/errorcode/PaymentErrorCode.java
  src/main/java/api/buyhood/domain/order/controller/OrderController.java
  src/main/java/api/buyhood/domain/order/dto/request/RefundPaymentReq.java
  src/main/java/api/buyhood/domain/order/service/OrderService.java
  src/main/java/api/buyhood/domain/payment/controller/PaymentRestController.java
  src/main/java/api/buyhood/domain/payment/entity/Payment.java
  src/main/java/api/buyhood/domain/payment/repository/PaymentRepository.java
  src/main/java/api/buyhood/domain/product/entity/Product.java
  src/main/java/api/buyhood/domain/product/service/ProductService.java
Labels: feat

#70 feat(MFLP-63): Developing Apply ZeroPay
  build.gradle
  buyhood-global-core/buyhood-global-common/src/main/java/api/errorcode/PaymentErrorCode.java
  src/main/java/api/buyhood/domain/payment/controller/PaymentController.java
  src/main/java/api/buyhood/domain/payment/controller/PaymentRestController.java
  src/main/java/api/buyhood/domain/payment/enums/PGProvider.java
  src/main/java/api/buyhood/domain/payment/service/PaymentService.java
  src/main/resources/templates/payment-qr.html
  src/main/resources/templates/payment-zeropay.html
Labels: feat

#72 feat(MFLP-64): Add zero pay success validation
  src/main/java/api/buyhood/domain/order/service/OrderService.java
  src/main/java/api/buyhood/domain/payment/controller/PaymentRestController.java
  src/main/java/api/buyhood/domain/payment/dto/request/ZPayValidationReq.java
  src/main/java/api/buyhood/domain/payment/service/PaymentService.java
Labels: feat

#74 faet(MFLP-69): Developing Cancel Order With ZeroPay
  buyhood-global-core/buyhood-global-common/src/main/java/api/buyhood/errorcode/PaymentErrorCode.java
  src/main/java/api/buyhood/domain/order/controller/OrderController.java
  src/main/java/api/buyhood/domain/order/dto/request/ZPRefundPaymentReq.java
  src/main/java/api/buyhood/domain/order/service/OrderService.java
  src/main/java/api/buyhood/domain/payment/enums/PayStatus.java
  src/main/java/api/buyhood/domain/payment/service/PaymentService.java
  src/main/java/api/buyhood/global/common/exception/enums/PaymentErrorCode.java
Labels: feat

#75 feat(MFLP-72): Testing & Developing Concurrency With Optimistic Lock
  build.gradle
  src/main/java/api/buyhood/domain/product/entity/Product.java
  src/main/java/api/buyhood/domain/product/repository/ProductRepository.java
  src/main/java/api/buyhood/domain/product/service/ProductService.java
  src/test/java/api/buyhood/concurrency/OrderWithOptimisticLockTest.java
  src/test/java/api/buyhood/concurrency/OrderWithoutLockTest.java
Labels: feat, test

#76 feat(MFLP-81): Dividing User Module & Implementing grant-SELLER and grant-ADMIN
  buyhood-global-core/buyhood-global-common/src/main/java/api/buyhood/errorcode/UserErrorCode.java
  buyhood-global-core/buyhood-global-config/build.gradle
  buyhood-user/build.gradle
  buyhood-user/src/main/java/api/buyhood/domain/user/BuyhoodDomainUserApplication.java
  buyhood-user/src/main/java/api/buyhood/domain/user/controller/UserController.java
  buyhood-user/src/main/java/api/buyhood/domain/user/dto/req/ChangeSellerRoleReq.java
  buyhood-user/src/main/java/api/buyhood/domain/user/dto/req/ChangeUserPasswordReq.java
  buyhood-user/src/main/java/api/buyhood/domain/user/dto/req/DeleteUserReq.java
  buyhood-user/src/main/java/api/buyhood/domain/user/dto/req/PatchUserReq.java
  buyhood-user/src/main/java/api/buyhood/domain/user/dto/res/GetUserRes.java
  buyhood-user/src/main/java/api/buyhood/domain/user/dto/res/PatchUserRes.java
  buyhood-user/src/main/java/api/buyhood/domain/user/entity/User.java
  buyhood-user/src/main/java/api/buyhood/domain/user/repository/UserRepository.java
  buyhood-user/src/main/java/api/buyhood/domain/user/service/UserService.java
Labels: feat, refactor

#77 feat(MFLP-79): Separate product domain modules
  buyhood-category/buyhood-product-category/src/main/java/api/buyhood/productcategory/controller/InternalProductCategoryController.java
  buyhood-category/buyhood-product-category/src/main/java/api/buyhood/productcategory/repository/InternalProductCategoryRepository.java
  buyhood-category/buyhood-product-category/src/main/java/api/buyhood/productcategory/service/InternalProductCategoryService.java
  buyhood-global-core/buyhood-global-common/src/main/java/api/buyhood/errorcode/CommonErrorCode.java
  buyhood-global-core/buyhood-global-common/src/main/java/api/buyhood/exception/ServerException.java
  buyhood-global-core/buyhood-global-feign/src/main/java/api/buyhood/client/ProductCategoryClient.java
  buyhood-global-core/buyhood-global-feign/src/main/java/api/buyhood/client/StoreClient.java
  buyhood-global-core/buyhood-global-feign/src/main/java/api/buyhood/client/UserClient.java
  buyhood-global-core/buyhood-global-feign/src/main/java/api/buyhood/dto/productcategory/ProductCategoryFeignDto.java
  buyhood-global-core/buyhood-global-feign/src/main/java/api/buyhood/dto/store/StoreFeignDto.java
  buyhood-product/src/main/java/api/buyhood/product/BuyHoodProductApplication.java
  buyhood-product/src/main/java/api/buyhood/product/client/ProductCategoryFeignClient.java
  buyhood-product/src/main/java/api/buyhood/product/client/StoreFeignClient.java
  buyhood-product/src/main/java/api/buyhood/product/client/UserFeignClient.java
  buyhood-product/src/main/java/api/buyhood/product/dto/request/PatchProductReq.java
  buyhood-product/src/main/java/api/buyhood/product/dto/request/RegisterProductReq.java
  buyhood-product/src/main/java/api/buyhood/product/dto/response/GetProductRes.java
  buyhood-product/src/main/java/api/buyhood/product/dto/response/PageProductRes.java
  buyhood-product/src/main/java/api/buyhood/product/dto/response/RegisterProductRes.java
  buyhood-product/src/main/java/api/buyhood/product/entity/Product.java
  buyhood-product/src/main/java/api/buyhood/product/entity/ProductCategoryMapping.java
  buyhood-product/src/main/java/api/buyhood/product/repository/ProductCategoryMappingRepository.java
  buyhood-product/src/main/java/api/buyhood/product/repository/ProductRepository.java
  buyhood-product/src/main/java/api/buyhood/product/service/ProductService.java
  buyhood-store/src/main/java/api/buyhood/store/controller/InternalStoreController.java
  buyhood-store/src/main/java/api/buyhood/store/repository/InternalStoreRepository.java
  buyhood-store/src/main/java/api/buyhood/store/service/InternalStoreService.java
  buyhood-store/src/main/java/api/buyhood/store/service/StoreService.java
  buyhood-user/src/main/java/api/buyhood/domain/user/controller/InternalUserController.java
  buyhood-user/src/main/java/api/buyhood/domain/user/service/InternalUserService.java
Labels: feat

#80 feat(MFLP-84): applying order FeignClient
  buyhood-global-core/buyhood-global-config/src/main/java/api/buyhood/config/SecurityConfig.java
  buyhood-global-core/buyhood-global-feign/src/main/java/api/buyhood/client/OrderClient.java
  buyhood-global-core/buyhood-global-feign/src/main/java/api/buyhood/dto/order/OrderFeignDto.java
  buyhood-order/src/main/java/api/buyhood/order/controller/InternalOrderController.java
  buyhood-order/src/main/java/api/buyhood/order/repository/InternalOrderRepository.java
  buyhood-order/src/main/java/api/buyhood/order/service/InternalOrderService.java
  buyhood-payment/build.gradle
  buyhood-payment/src/main/java/api/buyhood/payment/BuyhoodPaymentApplication.java
  buyhood-payment/src/main/java/api/buyhood/payment/controller/PaymentController.java
  buyhood-payment/src/main/java/api/buyhood/payment/controller/PaymentRestController.java
  buyhood-payment/src/main/java/api/buyhood/payment/entity/Payment.java
  buyhood-payment/src/main/java/api/buyhood/payment/repository/InternalPaymentRepository.java
  buyhood-payment/src/main/java/api/buyhood/payment/service/InternalPaymentService.java
  buyhood-payment/src/main/java/api/buyhood/payment/service/PaymentService.java
  buyhood-payment/src/main/resources/templates/payment-portone.html
  buyhood-payment/src/main/resources/templates/payment-qr.html
Labels: feat, refactor

#81 feat(MFLP-88) : Implement Product(register, patch, addcategory, removecategory, delete) & fix getStore ISSUE
  build.gradle
  buyhood-category/buyhood-product-category/src/main/java/api/buyhood/productcategory/dto/request/CreateProductCategoryReq.java
  buyhood-category/buyhood-product-category/src/main/java/api/buyhood/productcategory/dto/request/PatchProductCategoryReq.java
  buyhood-category/buyhood-product-category/src/main/java/api/buyhood/productcategory/service/InternalProductCategoryService.java
  buyhood-global-core/buyhood-global-config/src/main/java/api/buyhood/config/SecurityConfig.java
  buyhood-global-core/buyhood-global-feign/src/main/java/api/buyhood/client/ProductClient.java
  buyhood-global-core/buyhood-global-feign/src/main/java/api/buyhood/dto/product/ProductFeignDto.java
  buyhood-global-core/buyhood-global-feign/src/main/java/api/buyhood/dto/user/UserFeignDto.java
  buyhood-product/src/main/java/api/buyhood/product/BuyHoodProductApplication.java
  buyhood-product/src/main/java/api/buyhood/product/controller/ProductController.java
  buyhood-product/src/main/java/api/buyhood/product/dto/request/AddCategoryIdsReq.java
  buyhood-product/src/main/java/api/buyhood/product/dto/request/RemoveCategoryIdsReq.java
  buyhood-product/src/main/java/api/buyhood/product/repository/ProductRepository.java
  buyhood-product/src/main/java/api/buyhood/product/service/ProductQueryService.java
  buyhood-product/src/main/java/api/buyhood/product/service/ProductService.java
  buyhood-user/src/main/java/api/buyhood/domain/user/repository/UserRepository.java
  buyhood-user/src/main/java/api/buyhood/domain/user/service/InternalUserService.java
  src/main/java/api/buyhood/domain/auth/controller/AuthController.java
  src/main/java/api/buyhood/domain/auth/dto/req/SignInSellerReq.java
  src/main/java/api/buyhood/domain/auth/dto/req/SignInUserReq.java
  src/main/java/api/buyhood/domain/auth/dto/req/SignupSellerReq.java
  src/main/java/api/buyhood/domain/auth/dto/req/SignupUserReq.java
  src/main/java/api/buyhood/domain/auth/dto/res/SignInSellerRes.java
  src/main/java/api/buyhood/domain/auth/dto/res/SignInUserRes.java
  src/main/java/api/buyhood/domain/auth/dto/res/SignupSellerRes.java
  src/main/java/api/buyhood/domain/auth/dto/res/SignupUserRes.java
  src/main/java/api/buyhood/domain/auth/service/AuthService.java
  src/main/java/api/buyhood/domain/product/controller/ProductController.java
  src/main/java/api/buyhood/domain/product/dto/response/GetProductRes.java
  src/main/java/api/buyhood/domain/product/dto/response/PageProductRes.java
  src/main/java/api/buyhood/domain/product/dto/response/RegisterProductRes.java
  src/main/java/api/buyhood/domain/product/entity/Product.java
  src/main/java/api/buyhood/domain/product/entity/ProductCategoryMapping.java
  src/main/java/api/buyhood/domain/product/repository/ProductCategoryRepository.java
  src/main/java/api/buyhood/domain/product/repository/ProductRepository.java
  src/main/java/api/buyhood/domain/product/service/ProductService.java
  src/main/java/api/buyhood/domain/seller/controller/SellerController.java
  src/main/java/api/buyhood/domain/seller/dto/req/ChangeSellerPasswordReq.java
  src/main/java/api/buyhood/domain/seller/dto/req/DeleteSellerReq.java
  src/main/java/api/buyhood/domain/seller/dto/res/GetSellerRes.java
  src/main/java/api/buyhood/domain/seller/entity/Seller.java
  src/main/java/api/buyhood/domain/seller/repository/SellerRepository.java
  src/main/java/api/buyhood/domain/seller/service/SellerService.java
  src/main/java/api/buyhood/domain/user/controller/UserController.java
  src/main/java/api/buyhood/domain/user/dto/req/ChangeUserPasswordReq.java
  src/main/java/api/buyhood/domain/user/dto/req/DeleteUserReq.java
  src/main/java/api/buyhood/domain/user/dto/req/PatchUserReq.java
  src/main/java/api/buyhood/domain/user/dto/res/GetUserRes.java
  src/main/java/api/buyhood/domain/user/dto/res/PatchUserRes.java
  src/main/java/api/buyhood/domain/user/entity/User.java
  src/main/java/api/buyhood/domain/user/repository/UserRepository.java
  src/main/java/api/buyhood/domain/user/service/UserService.java
  src/main/java/api/buyhood/global/common/exception/enums/PaymentErrorCode.java
Labels: bug, feat

#84 refactor(MFLP-86): Refactor Payment Module
  buyhood-global-core/buyhood-global-common/src/main/java/api/buyhood/errorcode/PaymentErrorCode.java
  buyhood-global-core/buyhood-global-config/src/main/java/api/buyhood/handler/GlobalExceptionHandler.java
  buyhood-global-core/buyhood-global-feign/src/main/java/api/buyhood/dto/order/OrderFeignDto.java
  buyhood-payment/build.gradle
  buyhood-payment/src/main/java/api/buyhood/payment/BuyHoodPaymentApplication.java
  buyhood-payment/src/main/java/api/buyhood/payment/controller/InternalPaymentController.java
  buyhood-payment/src/main/java/api/buyhood/payment/controller/PaymentController.java
  buyhood-payment/src/main/java/api/buyhood/payment/controller/PaymentRestController.java
  buyhood-payment/src/main/java/api/buyhood/payment/dto/request/PaymentReq.java
  buyhood-payment/src/main/java/api/buyhood/payment/entity/Payment.java
  buyhood-payment/src/main/java/api/buyhood/payment/enums/PGProvider.java
  buyhood-payment/src/main/java/api/buyhood/payment/enums/PayStatus.java
  buyhood-payment/src/main/java/api/buyhood/payment/repository/PaymentRepository.java
  buyhood-payment/src/main/java/api/buyhood/payment/service/PaymentService.java
  buyhood-payment/src/main/resources/templates/payment-zeropay.html
  buyhood-payment/src/test/java/api/buyhood/payment/BuyHoodPaymentApplicationTests.java
  src/main/java/api/buyhood/domain/payment/controller/PaymentController.java
  src/main/java/api/buyhood/domain/payment/controller/PaymentRestController.java
  src/main/resources/templates/payment-portone.html
  src/main/resources/templates/payment-qr.html
Labels: bug, refactor

#85 chore(MFLP-86): add requestDto
  buyhood-payment/src/main/java/api/buyhood/payment/dto/request/PaymentReq.java
Labels: chore

#86 docs(MFLP-90): create basic README structure
  ReadMe.md
Labels: docs

#89 docs(MFLP-92): add API Documentation
  ReadMe.md
Labels: docs
