Repository Buyhood/BuyHood, pull requests merged in 2025-05, with the labels that each got.

#4 feat: Implementing category creation code
  .gitignore
  src/main/java/api/buyhood/domain/product/controller/CategoryController.java
  src/main/java/api/buyhood/domain/product/dto/request/CreateCategoryReq.java
  src/main/java/api/buyhood/domain/product/dto/response/CreateCategoryRes.java
  src/main/java/api/buyhood/domain/product/entity/Category.java
  src/main/java/api/buyhood/domain/product/repository/CategoryRepository.java
  src/main/java/api/buyhood/domain/product/service/CategoryService.java
  src/main/java/api/buyhood/global/common/exception/enums/CategoryErrorCode.java
Labels: feat

#5 feat: Implementing the InvalidException exception handling handler
  src/main/java/api/buyhood/global/common/dto/CustomExceptionDto.java
  src/main/java/api/buyhood/global/common/exception/enums/CartErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/CategoryErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/CommonErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/ErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/OrderErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/ProductErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/SellerErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/StoreErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/UserErrorCode.java
  src/main/java/api/buyhood/global/common/handler/GlobalExceptionHandler.java
Labels: feat

#7 refactor: Add markDeleted()
  src/main/java/api/buyhood/global/common/entity/BaseTimeEntity.java
Labels: feat

#10 feat(MFLP-14): Implementing the category get method
  src/main/java/api/buyhood/domain/product/controller/CategoryController.java
  src/main/java/api/buyhood/domain/product/dto/response/GetCategoryRes.java
  src/main/java/api/buyhood/domain/product/dto/response/PageCategoryRes.java
  src/main/java/api/buyhood/domain/product/entity/Category.java
  src/main/java/api/buyhood/domain/product/repository/CategoryRepository.java
  src/main/java/api/buyhood/domain/product/service/CategoryService.java
  src/main/java/api/buyhood/global/common/exception/enums/CategoryErrorCode.java
Labels: feat

#9 feat(MFLP-11): Developing the Add to Cart
  build.gradle
  src/main/java/api/buyhood/domain/cart/controller/CartController.java
  src/main/java/api/buyhood/domain/cart/dto/request/CartReq.java
  src/main/java/api/buyhood/domain/cart/dto/request/CreateCartReq.java
  src/main/java/api/buyhood/domain/cart/dto/response/CartItemRes.java
  src/main/java/api/buyhood/domain/cart/dto/response/CartRes.java
  src/main/java/api/buyhood/domain/cart/entity/Cart.java
  src/main/java/api/buyhood/domain/cart/entity/CartItem.java
  src/main/java/api/buyhood/domain/cart/repository/CartRepository.java
  src/main/java/api/buyhood/domain/cart/service/CartService.java
  src/main/java/api/buyhood/global/common/exception/enums/CartErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/CommonErrorCode.java
  src/main/java/api/buyhood/global/config/RedisConfig.java
  src/main/resources/application.properties
Labels: feat

#18 feat(MFLP-28): Implementing Login
  build.gradle
  src/main/java/api/buyhood/domain/auth/controller/AuthController.java
  src/main/java/api/buyhood/domain/auth/dto/req/SignInUserReq.java
  src/main/java/api/buyhood/domain/auth/dto/req/SigninUserReq.java
  src/main/java/api/buyhood/domain/auth/dto/res/SignInUserRes.java
  src/main/java/api/buyhood/domain/auth/service/AuthService.java
  src/main/java/api/buyhood/domain/user/repository/UserRepository.java
  src/main/java/api/buyhood/global/common/exception/enums/AuthErrorCode.java
Labels: feat

#17 feat(mflp-21): Implenmenting getUser & getAllUsers
  src/main/java/api/buyhood/domain/user/controller/UserController.java
  src/main/java/api/buyhood/domain/user/dto/res/GetUserRes.java
  src/main/java/api/buyhood/domain/user/repository/UserRepository.java
  src/main/java/api/buyhood/domain/user/service/UserService.java
  src/main/java/api/buyhood/global/common/exception/enums/UserErrorCode.java
Labels: feat

#13 feat(MFLP-12): Developing View Cart
  src/main/java/api/buyhood/domain/cart/controller/CartController.java
  src/main/java/api/buyhood/domain/cart/repository/CartRepository.java
  src/main/java/api/buyhood/domain/cart/service/CartService.java
  src/main/java/api/buyhood/global/common/exception/enums/CartErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/CommonErrorCode.java
Labels: feat

#21 feat(MFLP-29): Implementing the Product Registration API
  src/main/java/api/buyhood/domain/product/controller/ProductController.java
  src/main/java/api/buyhood/domain/product/dto/request/RegisteringProductReq.java
  src/main/java/api/buyhood/domain/product/dto/response/RegisteringProductRes.java
  src/main/java/api/buyhood/domain/product/service/ProductService.java
Labels: feat

#24 feat(MFLP-29): Implementing the Product Get API
  src/main/java/api/buyhood/domain/product/controller/ProductController.java
  src/main/java/api/buyhood/domain/product/dto/response/GetProductRes.java
  src/main/java/api/buyhood/domain/product/dto/response/PageProductRes.java
  src/main/java/api/buyhood/domain/product/repository/ProductRepository.java
  src/main/java/api/buyhood/domain/product/service/ProductService.java
  src/main/java/api/buyhood/global/common/exception/enums/ProductErrorCode.java
Labels: feat

#20 feat(MFLP-23): Implement changePassword
  src/main/java/api/buyhood/domain/user/controller/UserController.java
  src/main/java/api/buyhood/domain/user/dto/req/ChangePasswordReq.java
  src/main/java/api/buyhood/domain/user/entity/User.java
  src/main/java/api/buyhood/domain/user/repository/UserRepository.java
  src/main/java/api/buyhood/domain/user/service/UserService.java
  src/main/java/api/buyhood/global/common/exception/enums/UserErrorCode.java
  src/main/java/api/buyhood/global/common/filter/JwtAuthenticationFilter.java
Labels: feat

#26 feat(MFLP-31): Implement the product modification API
  src/main/java/api/buyhood/domain/product/controller/ProductController.java
  src/main/java/api/buyhood/domain/product/dto/request/PatchProductReq.java
  src/main/java/api/buyhood/domain/product/entity/Product.java
  src/main/java/api/buyhood/domain/product/repository/ProductRepository.java
  src/main/java/api/buyhood/domain/product/service/ProductService.java
  src/main/java/api/buyhood/global/common/exception/enums/ProductErrorCode.java
Labels: feat

#31 feat(MFLP-33): Implement the product delete API
  src/main/java/api/buyhood/domain/product/controller/ProductController.java
  src/main/java/api/buyhood/domain/product/service/ProductService.java
Labels: feat

#30 feat(MFLP- 22) : Implement deleteUser
  src/main/java/api/buyhood/domain/user/controller/UserController.java
  src/main/java/api/buyhood/domain/user/dto/req/DeleteUserReq.java
  src/main/java/api/buyhood/domain/user/entity/User.java
  src/main/java/api/buyhood/domain/user/service/UserService.java
Labels: feat

#32 feat(MFLP-24) : Implementing patchUser
  src/main/java/api/buyhood/domain/user/controller/UserController.java
  src/main/java/api/buyhood/domain/user/dto/req/PatchUserReq.java
  src/main/java/api/buyhood/domain/user/dto/res/PatchUserRes.java
  src/main/java/api/buyhood/domain/user/entity/User.java
  src/main/java/api/buyhood/domain/user/service/UserService.java
Labels: feat

#34 feat(MFLP-34) : Implement SellerSignUp
  src/main/java/api/buyhood/domain/auth/controller/AuthController.java
  src/main/java/api/buyhood/domain/auth/dto/req/SignupSellerReq.java
  src/main/java/api/buyhood/domain/auth/dto/res/SignupSellerRes.java
  src/main/java/api/buyhood/domain/auth/service/AuthService.java
  src/main/java/api/buyhood/domain/seller/entity/Seller.java
  src/main/java/api/buyhood/domain/seller/repository/SellerRepository.java
Labels: feat

#29 feat(MFLP-26): Developing Get Order
  src/main/java/api/buyhood/domain/order/controller/OrderHIsttoryController.java
  src/main/java/api/buyhood/domain/order/dto/response/OrderHistoryRes.java
  src/main/java/api/buyhood/domain/order/entity/OrderHistory.java
  src/main/java/api/buyhood/domain/order/repository/OrderHistoryRepository.java
  src/main/java/api/buyhood/domain/order/service/OrderHistoryService.java
  src/main/java/api/buyhood/global/common/exception/enums/OrderErrorCode.java
Labels: feat

#36 feat(MFLP-40): Implement the store get API
  src/main/java/api/buyhood/domain/store/controller/StoreController.java
  src/main/java/api/buyhood/domain/store/dto/response/GetStoreRes.java
  src/main/java/api/buyhood/domain/store/dto/response/PageStoreRes.java
  src/main/java/api/buyhood/domain/store/repository/StoreRepository.java
  src/main/java/api/buyhood/domain/store/service/StoreService.java
Labels: feat

#35 feat(MFLP-38) : Implement SellerSignIn
  src/main/java/api/buyhood/domain/auth/controller/AuthController.java
  src/main/java/api/buyhood/domain/auth/dto/req/SignInSellerReq.java
  src/main/java/api/buyhood/domain/auth/dto/res/SignInSellerRes.java
  src/main/java/api/buyhood/domain/auth/service/AuthService.java
  src/main/java/api/buyhood/domain/seller/repository/SellerRepository.java
  src/main/java/api/buyhood/domain/user/service/UserService.java
  src/main/java/api/buyhood/global/common/exception/enums/AuthErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/SellerErrorCode.java
  src/main/java/api/buyhood/global/common/exception/enums/UserErrorCode.java
Labels: bug, feat, refactor

#37 refactor(MFLP-44): refactoring unnecessary method and adding Authentication on Cart & Order
  src/main/java/api/buyhood/domain/cart/controller/CartController.java
  src/main/java/api/buyhood/domain/cart/dto/request/CartReq.java
  src/main/java/api/buyhood/domain/cart/dto/request/CreateCartReq.java
  src/main/java/api/buyhood/domain/cart/dto/response/CartItemRes.java
  src/main/java/api/buyhood/domain/cart/dto/response/CartRes.java
  src/main/java/api/buyhood/domain/cart/entity/Cart.java
  src/main/java/api/buyhood/domain/cart/entity/CartItem.java
  src/main/java/api/buyhood/domain/cart/repository/CartRepository.java
  src/main/java/api/buyhood/domain/cart/service/CartService.java
  src/main/java/api/buyhood/domain/order/dto/response/OrderHistoryRes.java
  src/main/java/api/buyhood/domain/order/entity/OrderHistory.java
  src/main/java/api/buyhood/domain/order/service/OrderHistoryService.java
Labels: refactor

#40 feat(MFLP-41): Implementing the store modification API
  src/main/java/api/buyhood/domain/store/controller/StoreController.java
  src/main/java/api/buyhood/domain/store/dto/request/PatchStoreReq.java
  src/main/java/api/buyhood/domain/store/entity/Store.java
  src/main/java/api/buyhood/domain/store/service/StoreService.java
  src/main/java/api/buyhood/global/common/exception/enums/StoreErrorCode.java
Labels: feat

#41 feat(MFLP-42): Implementing the store delete API
  src/main/java/api/buyhood/domain/store/controller/StoreController.java
  src/main/java/api/buyhood/domain/store/service/StoreService.java
Labels: feat

#42 feat(MFLP-46) : Implement ApplyOrder & ApproveOrder & RejectOrder
  src/main/java/api/buyhood/domain/order/controller/OrderController.java
  src/main/java/api/buyhood/domain/order/controller/OrderHistoryController.java
  src/main/java/api/buyhood/domain/order/dto/request/AcceptOrderReq.java
  src/main/java/api/buyhood/domain/order/dto/request/ApplyOrderReq.java
  src/main/java/api/buyhood/domain/order/dto/request/CreateOrderReq.java
  src/main/java/api/buyhood/domain/order/dto/response/AcceptOrderRes.java
  src/main/java/api/buyhood/domain/order/dto/response/ApplyOrderRes.java
  src/main/java/api/buyhood/domain/order/dto/response/RejectOrderRes.java
  src/main/java/api/buyhood/domain/order/entity/Order.java
  src/main/java/api/buyhood/domain/order/enums/OrderStatus.java
  src/main/java/api/buyhood/domain/order/repository/OrderRepository.java
  src/main/java/api/buyhood/domain/order/service/OrderService.java
  src/main/java/api/buyhood/global/common/exception/ForbiddenException.java
  src/main/java/api/buyhood/global/common/exception/enums/OrderErrorCode.java
  src/main/java/api/buyhood/global/config/SecurityConfig.java
Labels: feat

#38 feat(MFLP-35): Implement GetSeller & GetSellers
  src/main/java/api/buyhood/domain/seller/controller/SellerController.java
  src/main/java/api/buyhood/domain/seller/dto/req/DeleteSellerReq.java
  src/main/java/api/buyhood/domain/seller/dto/res/GetSellerRes.java
  src/main/java/api/buyhood/domain/seller/entity/Seller.java
  src/main/java/api/buyhood/domain/seller/repository/SellerRepository.java
  src/main/java/api/buyhood/domain/seller/service/SellerService.java
Labels: feat

#46 feat(MFLP-50): Added CategoryProduct entity and modified associated code
  src/main/java/api/buyhood/domain/product/controller/ProductController.java
  src/main/java/api/buyhood/domain/product/dto/request/PatchProductReq.java
  src/main/java/api/buyhood/domain/product/dto/request/RegisterProductReq.java
  src/main/java/api/buyhood/domain/product/dto/response/GetProductRes.java
  src/main/java/api/buyhood/domain/product/dto/response/PageProductRes.java
  src/main/java/api/buyhood/domain/product/dto/response/RegisterProductRes.java
  src/main/java/api/buyhood/domain/product/entity/CategoryProduct.java
  src/main/java/api/buyhood/domain/product/entity/Product.java
  src/main/java/api/buyhood/domain/product/repository/CategoryProductRepository.java
  src/main/java/api/buyhood/domain/product/repository/CategoryRepository.java
  src/main/java/api/buyhood/domain/product/repository/ProductRepository.java
  src/main/java/api/buyhood/domain/product/service/CategoryService.java
  src/main/java/api/buyhood/domain/product/service/ProductService.java
Labels: feat

#44 feat(MFLP-36) : Implement changeSellerPassword & adding config path
  src/main/java/api/buyhood/domain/auth/dto/req/SignInUserReq.java
  src/main/java/api/buyhood/domain/auth/dto/req/SignupSellerReq.java
  src/main/java/api/buyhood/domain/auth/dto/req/SignupUserReq.java
  src/main/java/api/buyhood/domain/auth/service/AuthService.java
  src/main/java/api/buyhood/domain/cart/dto/request/CartReq.java
  src/main/java/api/buyhood/domain/order/dto/request/AcceptOrderReq.java
  src/main/java/api/buyhood/domain/order/dto/request/ApplyOrderReq.java
  src/main/java/api/buyhood/domain/seller/controller/SellerController.java
  src/main/java/api/buyhood/domain/seller/dto/req/ChangeSellerPasswordReq.java
  src/main/java/api/buyhood/domain/seller/dto/req/DeleteSellerReq.java
  src/main/java/api/buyhood/domain/seller/dto/res/GetSellerRes.java
  src/main/java/api/buyhood/domain/seller/entity/Seller.java
  src/main/java/api/buyhood/domain/seller/service/SellerService.java
  src/main/java/api/buyhood/domain/user/controller/UserController.java
  src/main/java/api/buyhood/domain/user/dto/req/ChangeUserPasswordReq.java
  src/main/java/api/buyhood/domain/user/entity/User.java
  src/main/java/api/buyhood/domain/user/service/UserService.java
  src/main/java/api/buyhood/global/config/SecurityConfig.java
Labels: feat, refactor

#47 refactor(MFLP-30): Add categoryId field to category ResponseDTO
  src/main/java/api/buyhood/domain/product/dto/response/CreateCategoryRes.java
  src/main/java/api/buyhood/domain/product/dto/response/GetCategoryRes.java
  src/main/java/api/buyhood/domain/product/dto/response/PageCategoryRes.java
Labels: refactor
